import React from 'react';
import { Link } from 'react-router-dom'
import Footer from '../components/Footer'

function TermsConditions(props) {
     
    return (
        <React.Fragment>
            <div className="privacy-policy">
                <div className='hdr flex wrapPadding rel' style={{background: 'url(/images/tc-wave.svg)'}}>
                    <Link to="/" className='logo flex aic'>
                        <img src="/images/logo.png" className="img" />
                        <div className="tt font s22 b8 black">ShopEagle</div>
                    </Link>
                    <div className='wrap flex flex-col aic rel'>
                        <div className='title font b7 s32'>Terms & Conditions</div>
                    </div> 
                </div> 
                <div className="content flex flex-col">
                    <div className='actions flex aic'>
                        <div className='lef flex flex-col'>
                            <div className='btns flex aic c69'>
                                <Link to="/" className="btn font s16 c69">Go to Home</Link>
                                <span>&nbsp;&nbsp;&#47;&nbsp;&nbsp;</span>
                                <Link to="/terms-conditions" className="btn font s16 c69">Terms Conditions</Link>
                            </div>
                        </div>
                    </div>
                    <div className="item">
                        <div className="txt marg-btm font s16 c69">Yes, we use Google Maps for the purpose of providing better service. This website, mobile application, or Facebook application uses Google Maps APIs. You may find the Google Maps APIs Terms of Service here. To better understand Google’s Privacy Policy, please refer to this link. By using our Maps API Implementation, you agree to be bound by Google’s Terms of Service. By using our implementation of the Google Maps APIs, you agree to allow us to gain access to information about you including personally identifiable information (such as usernames) and non-personally identifiable information (such as location). We will be collecting the following information. For a full list of what we use information for, please see the previous section titled The Maps APIs that we use store and access cookies and other information on your devices. If you are a user currently in the European Economic Area EU countries, Iceland, Liechtenstein and Norway please take a look at our EU User Consent Policy.</div>
                        <div className="txt marg-btm font s16 c69">If you choose to register or log in to our services using a social media account, we may have access to certain information about you. Our Services or Apps offer you the ability to register and login using your third party social media account details (like your Facebook or Twitter logins). Where you choose to do this, we will receive certain profile information about you from your social media provider. The profile Information we receive may vary depending on the social media provider concerned, but will often include your name, e-mail address, friends list, profile picture as well as other information you choose to make public. You agree to allow us to obtain or cache your location. You may revoke your consent at anytime. We use information about location in conjunction with data from other data providers. The Maps APIs that we use store and access cookies and other information on your devices. If you are a user currently in the European Economic Area EU countries, Iceland, Liechtenstein and Norway please take a look at our EU User Consent Policy.</div>
                        <div className="txt marg-btm font s16 c69">If you choose to register or log in to our services using a social media account, we may have access to certain information about you. Our Services or Apps offer you the ability to register and login using your third party social media account details (like your Facebook or Twitter logins). Where you choose to do this, we will receive certain profile information about you from your social media provider. The profile Information we receive may vary depending on the social media provider concerned, but will often include your name, e-mail address, friends list, profile picture as well as other information you choose to make public.</div>
                    </div>
                      
                    <div className="heading flex flex-col"> 
                        <a href="#OurPrivacy" className='lin font s16 c69'>1.&nbsp;<span className='noul'>Our Privacy Policy</span></a> 
                        <a href="#Information" className='lin font s16 c69'>2.&nbsp;<span className='noul'>Information Collected or Received</span></a>
                        <a href="#Findablility" className='lin font s16 c69'>3.&nbsp;<span className='noul'>Findablility</span></a>
                        <a href="#MessagefromEsty" className='lin font s16 c69'>4.&nbsp;<span className='noul'>Message from Etsy</span></a>
                        <div className='lin font s16 c69'>5.&nbsp;<span className='noul'>Community</span></div>
                        <div className='lin font s16 c69'>6.&nbsp;<span className='noul'>Information Uses, Sharing & Disclosure</span></div>
                        <div className='lin font s16 c69'>7.&nbsp;<span className='noul'>Transfers</span></div>
                        <div className='lin font s16 c69'>8.&nbsp;<span className='noul'>Security</span></div>
                        <div className='lin font s16 c69'>9.&nbsp;<span className='noul'>Retention</span></div>
                        <div className='lin font s16 c69'>10.&nbsp;<span className='noul'>Your Rights & Choices</span></div>
                        <div className='lin font s16 c69'>11.&nbsp;<span className='noul'>Your Responsibilities</span></div>
                        <div className='lin font s16 c69'>12.&nbsp;<span className='noul'>Privacy Policy Changes</span></div>
                        <div className='lin font s16 c69'>13.&nbsp;<span className='noul'>Contact</span></div>
                    </div>
  
                    <div id="OurPrivacy" className="item">
                        <div className='lbl font s26 b8 c000'>1. Our Privacy Policy</div>
                        <div className='txt font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content has not been verified or approved by us and the views expressed by other users on the Site do not represent our views or values. Except as expressly provided in these Terms and Conditions, no part of the Site, Services or Our Content may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, without our express prior written permission.</div>
                        <div className='txt font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content has not been verified or approved by us and the views expressed by other users on the Site do not represent our views or values. Except as expressly provided in these Terms and Conditions, no part of the Site, Services or Our Content may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.</div>
                        <div className='txt marg-btm font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content has not been verified or approved by us and the views expressed by other users on the Site do not represent our views or values. Except as expressly provided in these Terms and Conditions, no part of the Site, Services or Our Content may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise.</div>
                    </div>
                    <div id="Information" className="item">
                        <div className='lbl font s26 b8 c000'>2. Information Collected or Received</div>
                        <div className='txt font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content has not been verified or approved by us and the views expressed by other users on the Site do not represent our views or values. Except as expressly provided in these Terms and Conditions, no part of the Site, Services or Our Content may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise exploited for any commercial purpose whatsoever, without our express prior written permission.</div>
                        <div className='txt marg-btm font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content has not been verified or approved by us and the views expressed by other users on the Site do not represent our views or values. Except as expressly provided in these Terms and Conditions, no part of the Site, Services or Our Content may be copied, reproduced, aggregated, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, distributed, sold, licensed, or otherwise. You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content has not been verified or approved by us and the views expressed by other users on the Site do not represent our views or values.</div>
                    </div>
                    <div id="Findablility" className="item">
                        <div className='lbl font s26 b8 c000'>3. Findablility</div>
                        <div className='txt font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content do not represent our views or values.</div>
                        <div className='txt font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content has not been verified </div>
                        <div className='txt marg-btm font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User the Site do not represent our views or values.</div>
                    </div>
                    <div id="MessagefromEsty" className="item">
                        <div className='lbl font s22 b8 c000'>4. Message from Etsy</div>
                        <div className='txt font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content do not represent our views or values.</div>
                        <div className='txt font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User Content has not been verified </div>
                        <div className='txt font s16 c69'>You warrant that any User Content does comply with our Acceptable Use Policy, and you will be liable to us and indemnify us for any breach of that warranty. This means you will be responsible for any loss or damage we suffer as a result of your breach of this warranty. We are not responsible and accept no liability for any User Content including any such content that contains incorrect information or is defamatory or loss of User Content. We accept no obligation to screen, edit or monitor any User Content but we reserve the right to remove, screen and/or edit any User Content without notice and at any time. User the Site do not represent our views or values.</div>
                    </div>
                </div>
            </div>
            <Footer/>
        </React.Fragment>

    );
}
 
export default TermsConditions;